[head_node]
localhost ansible_user=kei ansible_become=yes

[compute_nodes]
compute_node_1 ansible_host=10.0.0.2 ansible_user=kei ansible_become=yes
compute_node_2 ansible_host=10.0.0.3 ansible_user=kei ansible_become=yes
